[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "SRinputs"
version = "0.2.0"
authors = [
  { name="Keiner Mendoza", email="keynerismo@gmail.com" },
]
description = "A Python suite for safe user inputs (SR) and automated fake data simulation (FR) using Faker."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Education",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "fast_langdetect",
    "faker",
]

[project.urls]
Homepage = "https://github.com/keyles-Py/SRinputs"
Bug_Tracker = "https://github.com/keyles-Py/SRinputs/issues"