import sys
from faker import Faker
from time import sleep
import io

"""Name, Url, Mail, Date, PhoneNumber, Id, Handle"""
wait = 0.4

fake = Faker()

GENDERS = {
        'male' : fake.name_male,
        'female' : fake.name_female,
        'nonbinary' : fake.name_nonbinary,
        'default' : fake.name
    }

DATE_FORMATS = ["%Y-%m-%d", "%d/%m/%Y", "%m-%d-%Y", "%d/%m/%y"]

def FRNameInput(msg : str = 'Write a name: ', gender : str = 'default'):
    """
    Generates a fake name based on gender and simulates it as standard input.

    The function temporarily redirects sys.stdin to a string generated by the 
    Faker library, allowing the input() function to read a random name.

    Args:
        msg (str, optional): The message to display to the user. Defaults to 'Write a name: '.
        gender (str, optional): The gender category for the name ('male', 'female', 'nonbinary', 'default'). 
                                Defaults to 'default'.
    Returns:
        str: The fake name generated and read from the simulated input.
    """
    temp_stdin = sys.stdin
    try:
        clean_gender = gender.lower()
        if clean_gender not in GENDERS:
            clean_gender = 'default'
        sys.stdin = io.StringIO(GENDERS.get(clean_gender)())
        name = input(msg)
        sleep(wait)
        print(name)
        return name
    
    except TypeError as e:
        print(f'Error: {e}')
    finally:  
        sys.stdin = temp_stdin

def FRUrlInput(msg : str = 'Write your link: '):
    """
    Generates a fake URL and simulates it as standard input.

    The function temporarily redirects sys.stdin to a URL generated by the 
    Faker library, allowing the input() function to read a random link.

    Args:
        msg (str, optional): The message to display to the user. Defaults to 'Write your link: '.

    Returns:
        str: The fake URL generated and read from the simulated input.
    """
    temp_stdin = sys.stdin
    try:
        sys.stdin = io.StringIO(fake.url())
        url = input(msg)
        sleep(wait)
        print(url)
        return url 
    
    except Exception as e:
        print(f"Error {e}")
    finally:
        sys.stdin = temp_stdin

def FREmailInput(msg : str = "Write your Email: "):
    """
    Generates a fake email address and simulates it as standard input.

    The function temporarily redirects sys.stdin to an email generated by the 
    Faker library, allowing the input() function to read a random address.

    Args:
        msg (str, optional): The message to display to the user. Defaults to 'Write your Email: '.

    Returns:
        str: The fake email address generated and read from the simulated input.
    """
    temp_stdin = sys.stdin
    try:
        sys.stdin = io.StringIO(fake.email())
        email = input(msg)
        sleep(wait)
        print(email)
        return email
    
    except Exception as e:
        print(f"Error {e}")
    finally:
        sys.stdin = temp_stdin

def FRDateInput(msg : str = "Write your birthday: ", format : int = 0):
    """
    Generates a fake date and simulates it as standard input.

    The function temporarily redirects sys.stdin to a date generated by the 
    Faker library using a specific format from a predefined list, allowing 
    the input() function to read a random date string.

    Args:
        msg (str, optional): The message to display to the user. Defaults to 'Write your birthday: '.
        format (int, optional): The index of the date format to use (0 to 3). Defaults to 0.

    Returns:
        str: The fake date generated and read from the simulated input.
    """
    temp_stdin = sys.stdin
    try:
        format = int(format)
        safeIndex = format % len(DATE_FORMATS)
        sys.stdin = io.StringIO(fake.date(DATE_FORMATS[safeIndex]))
        date = input(msg)
        sleep(wait)
        print(date)
        return date
    
    except ValueError:
        print(f"The format value must be an integer between 0 and 3 not {format}")
    except Exception as e:
        print(f"Error {e}")
    finally:
        sys.stdin = temp_stdin

def FRPhoneNumInput(msg :  str = "Write your phone number: "):
    """
    Generates a fake phone number and simulates it as standard input.

    The function temporarily redirects sys.stdin to a phone number generated by the 
    Faker library, allowing the input() function to read a random contact number.

    Args:
        msg (str, optional): The message to display to the user. Defaults to 'Write your phone number: '.

    Returns:
        str: The fake phone number generated and read from the simulated input.
    """
    temp_stdin = sys.stdin
    try:
        sys.stdin = io.StringIO(fake.phone_number())
        phoneNumber = input(msg)
        sleep(wait)
        print(phoneNumber)
        return phoneNumber
    
    except Exception as e:
        print(f"Error: {e}")
    finally:
        sys.stdin = temp_stdin

def FRIdInput(msg : str = "Write your id: "):
    """
    Generates a fake identification number (ID) and simulates it as standard input.

    The function temporarily redirects sys.stdin to a randomized numeric string 
    of variable length (8 to 10 digits) generated via specific placeholders, 
    allowing the input() function to read a random identifier.

    Args:
        msg (str, optional): The message to display to the user. Defaults to 'Write your id: '.

    Returns:
        str: The fake ID generated and read from the simulated input.
    """
    temp_stdin = sys.stdin
    try:
        sys.stdin = io.StringIO(fake.numerify("@@%%%%%%%%"))
        Id = input(msg)
        sleep(wait)
        print(Id)
        return Id
    
    except Exception as e:
        print(f"Error: {e}")
    finally:
        sys.stdin = temp_stdin

def FRHandleInput(msg : str = "Write your handle: ", name : str = ""):
    """
    Generates a fake social media handle and simulates it as standard input.

    The function constructs a handle starting with '@', using a portion of a 
    provided or generated name, and appends random digits. It then redirects 
    sys.stdin to this handle, allowing the input() function to read it.

    Args:
        msg (str, optional): The message to display to the user. Defaults to 'Write your handle: '.
        name (str, optional): A base name to construct the handle. If not provided, 
                              a random name is generated.

    Returns:
        str: The fake social media handle generated and read from the simulated input.
    """
    temp_stdin = sys.stdin
    try:
        if not name:
            name = fake.name().replace(" ", "")
        
        auxHandle = "@" + name[:len(name)//3] + "_" + name[1 + len(name)//3:] +  fake.numerify("@@@@")
        sys.stdin = io.StringIO(auxHandle)
        handle = input(msg)
        sleep(wait)
        print(handle)
        return handle
    
    except Exception as e:
        print(f"Error: {e}")
    finally:
        sys.stdin = temp_stdin